"""V 1.1 add active status of user

Revision ID: 3b6c8b8be5ab
Revises: 70b8440aa8bc
Create Date: 2017-11-17 11:26:11.450522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b6c8b8be5ab'
down_revision = '70b8440aa8bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active_status', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'active_status')
    # ### end Alembic commands ###
