"""add category type

Revision ID: 6c6f5f835ebb
Revises: 8c8e9d2a678d
Create Date: 2017-10-28 10:48:57.632377

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c6f5f835ebb'
down_revision = '8c8e9d2a678d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('category_name', sa.String(length=255), nullable=False))
    op.add_column('category', sa.Column('category_type', sa.SmallInteger(), nullable=False))
    op.drop_column('category', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('category', 'category_type')
    op.drop_column('category', 'category_name')
    # ### end Alembic commands ###
