"""V1.0 add category order

Revision ID: 70b8440aa8bc
Revises: 806274d12d4c
Create Date: 2017-11-14 09:45:03.095260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70b8440aa8bc'
down_revision = '806274d12d4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('category_order', sa.SmallInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'category_order')
    # ### end Alembic commands ###
