"""add category name

Revision ID: 806274d12d4c
Revises: 6c6f5f835ebb
Create Date: 2017-10-28 17:25:14.678738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '806274d12d4c'
down_revision = '6c6f5f835ebb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('image_id', sa.CHAR(length=36), nullable=False),
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('create_time', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('image_id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_image_create_time'), 'image', ['create_time'], unique=False)
    op.create_index(op.f('ix_image_user_id'), 'image', ['user_id'], unique=False)
    op.add_column('category', sa.Column('create_time', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_category_create_time'), 'category', ['create_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_create_time'), table_name='category')
    op.drop_column('category', 'create_time')
    op.drop_index(op.f('ix_image_user_id'), table_name='image')
    op.drop_index(op.f('ix_image_create_time'), table_name='image')
    op.drop_table('image')
    # ### end Alembic commands ###
