"""Version 1

Revision ID: af057997da7a
Revises: 
Create Date: 2017-10-12 21:51:20.454623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af057997da7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('article_id', sa.CHAR(length=36), nullable=False),
    sa.Column('category_id', sa.CHAR(length=36), nullable=True),
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('update_time', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('article_id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_article_category_id'), 'article', ['category_id'], unique=False)
    op.create_index(op.f('ix_article_create_time'), 'article', ['create_time'], unique=False)
    op.create_index(op.f('ix_article_update_time'), 'article', ['update_time'], unique=False)
    op.create_index(op.f('ix_article_user_id'), 'article', ['user_id'], unique=False)
    op.create_table('category',
    sa.Column('category_id', sa.CHAR(length=36), nullable=False),
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('category_id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_category_user_id'), 'category', ['user_id'], unique=False)
    op.create_table('user',
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('pswd', sa.CHAR(length=32), nullable=False),
    sa.Column('create_time', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_user_create_time'), 'user', ['create_time'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_create_time'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_category_user_id'), table_name='category')
    op.drop_table('category')
    op.drop_index(op.f('ix_article_user_id'), table_name='article')
    op.drop_index(op.f('ix_article_update_time'), table_name='article')
    op.drop_index(op.f('ix_article_create_time'), table_name='article')
    op.drop_index(op.f('ix_article_category_id'), table_name='article')
    op.drop_table('article')
    # ### end Alembic commands ###
